# Generated by Django 5.2.7 on 2025-10-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_cliente_user_alter_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.AddField(
            model_name='empleado',
            name='puestos',
            field=models.ManyToManyField(blank=True, to='applications.servicios'),
        ),
    ]
